### PR TITLE
added custom headers on trigger

### PR DESCRIPTION
**Pull request by alopezvillaverde**
Including custom headers on trigger webHook if provided

### CODE REVIEW

**Comment by roccomuso** [comment]
Great. Let me review it and then I'll merge. :)
I was also thinking about a complete module rewritten. This module was written in a rush. Would not be bad to better optimize the code.

**Comment by roccomuso** [comment]
thank you. Publishing soon the new version on NPM.

**Comment by roccomuso** [comment]
@alopezvillaverde I Just want to let you know that <code>Object.assign</code> https://github.com/roccomuso/node-webhooks/blob/master/index.js#L91 is not available for node v0.12 and older. That's why this build failed: https://travis-ci.org/roccomuso/node-webhooks/jobs/156587904
we should find an alternative to be able to support older versions of node.

**Comment by alopezvillaverde** [comment]
@roccomuso I saw the `lodash` merge change. Perfect!

**Pull request merged**
